import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';

// Generate incident report HTML content
function generateReportHTML(data: {
    title: string;
    date: string;
    severity: string;
    summary: string;
    timeline: { time: string; event: string; type: string }[];
    evidence: { name: string; type: string; hash: string; size: string }[];
    recommendations: string[];
}): string {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${data.title}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #333; }
    h1 { color: #2E3440; border-bottom: 3px solid #BF616A; padding-bottom: 10px; }
    h2 { color: #4C566A; margin-top: 30px; border-bottom: 1px solid #ddd; padding-bottom: 8px; }
    .header-info { background: #f5f5f5; padding: 15px; border-radius: 8px; margin: 20px 0; }
    .header-info p { margin: 5px 0; }
    .severity-high { color: #BF616A; font-weight: bold; }
    .severity-medium { color: #EBCB8B; font-weight: bold; }
    .severity-low { color: #A3BE8C; font-weight: bold; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
    th { background: #4C566A; color: white; }
    tr:nth-child(even) { background: #f9f9f9; }
    .timeline-item { padding: 10px; border-left: 3px solid #88C0D0; margin: 10px 0; background: #f9f9f9; }
    .timeline-item.critical { border-left-color: #BF616A; }
    .timeline-item.warning { border-left-color: #EBCB8B; }
    .timeline-time { font-weight: bold; color: #4C566A; }
    ul { padding-left: 20px; }
    li { margin: 8px 0; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <h1>🛡️ ${data.title}</h1>
  
  <div class="header-info">
    <p><strong>Date:</strong> ${data.date}</p>
    <p><strong>Severity:</strong> <span class="severity-${data.severity.toLowerCase()}">${data.severity}</span></p>
    <p><strong>Report ID:</strong> IR-${Date.now()}</p>
  </div>
  
  <h2>Executive Summary</h2>
  <p>${data.summary}</p>
  
  <h2>Timeline of Events</h2>
  ${data.timeline.map(item => `
    <div class="timeline-item ${item.type}">
      <span class="timeline-time">${item.time}</span> - ${item.event}
    </div>
  `).join('')}
  
  <h2>Evidence Collected</h2>
  <table>
    <thead>
      <tr>
        <th>File Name</th>
        <th>Type</th>
        <th>SHA256 Hash</th>
        <th>Size</th>
      </tr>
    </thead>
    <tbody>
      ${data.evidence.map(item => `
        <tr>
          <td>${item.name}</td>
          <td>${item.type}</td>
          <td><code>${item.hash}</code></td>
          <td>${item.size}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  
  <h2>Recommended Actions</h2>
  <ul>
    ${data.recommendations.map(rec => `<li>${rec}</li>`).join('')}
  </ul>
  
  <h2>CERT-In Reporting Guidelines</h2>
  <p>As per Indian Computer Emergency Response Team (CERT-In) guidelines, this incident should be reported within 6 hours of detection. Key information to include:</p>
  <ul>
    <li>Nature of incident and affected systems</li>
    <li>Timeline of attack</li>
    <li>Indicators of Compromise (IOCs)</li>
    <li>Actions taken for containment</li>
    <li>Contact information for follow-up</li>
  </ul>
  
  <div class="footer">
    <p>Generated by Arishadvarga-Guardian Cyber Defense Platform</p>
    <p>Report Date: ${new Date().toISOString()}</p>
  </div>
</body>
</html>`;
}

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { format, data } = body;

        if (format === 'pdf') {
            // Generate HTML report (can be opened in browser and printed to PDF)
            const htmlContent = generateReportHTML(data);

            return new NextResponse(htmlContent, {
                headers: {
                    'Content-Type': 'text/html',
                    'Content-Disposition': `attachment; filename="incident-report-${Date.now()}.html"`,
                },
            });

        } else if (format === 'zip') {
            // Create ZIP bundle with all evidence and report
            const zip = new JSZip();

            // Add the HTML report
            const htmlContent = generateReportHTML(data);
            zip.file('incident-report.html', htmlContent);

            // Add timeline as JSON
            zip.file('timeline.json', JSON.stringify(data.timeline, null, 2));

            // Add evidence list
            zip.file('evidence-manifest.json', JSON.stringify(data.evidence, null, 2));

            // Add IOCs file
            const iocs = {
                ips: data.ips || ['45.33.32.156', '103.224.182.251'],
                hashes: data.evidence.map((e: { hash: string }) => e.hash),
                domains: data.domains || [],
                generatedAt: new Date().toISOString(),
            };
            zip.file('iocs.json', JSON.stringify(iocs, null, 2));

            // Add README
            zip.file('README.txt', `
Arishadvarga-Guardian Incident Report Bundle
=============================================

This ZIP contains:
- incident-report.html  : Full incident report (open in browser)
- timeline.json        : Event timeline in JSON format
- evidence-manifest.json: List of collected evidence with hashes
- iocs.json           : Indicators of Compromise for blocking

Generated: ${new Date().toISOString()}
Report ID: IR-${Date.now()}

For questions, contact your security team.
`);

            // Generate ZIP file as blob and convert to ArrayBuffer for NextResponse
            const zipBlob = await zip.generateAsync({ type: 'blob' });
            const zipArrayBuffer = await zipBlob.arrayBuffer();

            return new NextResponse(zipArrayBuffer, {
                headers: {
                    'Content-Type': 'application/zip',
                    'Content-Disposition': `attachment; filename="incident-bundle-${Date.now()}.zip"`,
                },
            });

        } else {
            return NextResponse.json({ error: 'Invalid format. Use "pdf" or "zip".' }, { status: 400 });
        }

    } catch (error) {
        console.error('Export error:', error);
        return NextResponse.json(
            { error: error instanceof Error ? error.message : 'Export failed' },
            { status: 500 }
        );
    }
}
